version: '3.8'

services:
  mysql:
    image: mysql:8.0.44
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: Polaris6432
      MYSQL_DATABASE: polaris
      MYSQL_USER: polarisAdmin
      MYSQL_PASSWORD: Polaris6432
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb3
      - --collation-server=utf8mb3_general_ci
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: phpMyAdmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100M
    ports:
      - "3307:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data: